spring.application.name=playlist

# Configuração do Banco de Dados MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/playlist_db?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=28062019
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Para criar as tabelas automaticamente
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect